# -*- coding: utf-8 -*-
"""Library_Management_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kK8sBAYQKjvNfDpEaqdQIEejLakhyA-u
"""

books = []

def add_book():
    book_id = int(input("Enter Book ID: "))

    for book in books:
        if book["id"] == book_id:
            print("Book ID already exists!")
            return

    name = input("Enter Book Name: ")
    author = input("Enter Author Name: ")

    book = {
        "id": book_id,
        "name": name,
        "author": author,
        "status": "Available"
    }

    books.append(book)
    print("Book Added Successfully!")


def view_books():
    if not books:
        print("No Books Available!")
        return

    print("\n===== BOOK LIST =====")
    for book in books:
        print(
            f"ID: {book['id']} | "
            f"Book: {book['name']} | "
            f"Author: {book['author']} | "
            f"Status: {book['status']}"
        )


def search_book():
    book_id = int(input("Enter Book ID to Search: "))

    for book in books:
        if book["id"] == book_id:
            print("\nBook Found!")
            print(
                f"ID: {book['id']} | "
                f"Book: {book['name']} | "
                f"Author: {book['author']} | "
                f"Status: {book['status']}"
            )
            return

    print("Book Not Found!")


def issue_book():
    book_id = int(input("Enter Book ID to Issue: "))

    for book in books:
        if book["id"] == book_id:

            if book["status"] == "Issued":
                print("Book Already Issued!")
                return

            book["status"] = "Issued"
            print("Book Issued Successfully!")
            return

    print("Book Not Found!")


def return_book():
    book_id = int(input("Enter Book ID to Return: "))

    for book in books:
        if book["id"] == book_id:

            if book["status"] == "Available":
                print("Book is Already Available!")
                return

            book["status"] = "Available"
            print("Book Returned Successfully!")
            return

    print("Book Not Found!")


def delete_book():
    book_id = int(input("Enter Book ID to Delete: "))

    for book in books:
        if book["id"] == book_id:
            books.remove(book)
            print("Book Deleted Successfully!")
            return

    print("Book Not Found!")


def available_books():
    print("\n===== AVAILABLE BOOKS =====")

    found = False

    for book in books:
        if book["status"] == "Available":
            found = True
            print(
                f"ID: {book['id']} | "
                f"Book: {book['name']} | "
                f"Author: {book['author']}"
            )

    if not found:
        print("No Available Books!")


while True:

    print("\n===== LIBRARY MANAGEMENT SYSTEM =====")
    print("1. Add Book")
    print("2. View Books")
    print("3. Search Book")
    print("4. Issue Book")
    print("5. Return Book")
    print("6. Delete Book")
    print("7. Show Available Books")
    print("8. Exit")

    choice = input("Enter Choice: ")

    if choice == "1":
        add_book()

    elif choice == "2":
        view_books()

    elif choice == "3":
        search_book()

    elif choice == "4":
        issue_book()

    elif choice == "5":
        return_book()

    elif choice == "6":
        delete_book()

    elif choice == "7":
        available_books()

    elif choice == "8":
        print("Program Closed!")
        break

    else:
        print("Invalid Choice!")

